spring:
 config: 
  activate:
   on-profile: "qa"

build: 
 version: "2.0"

accounts:
 message: "Welcome to accounts API AQ TESTER"
 contactDetails: 
  name: "JuanHiguita"
  email: "juan@correo.com"
 OncallSupport: 
  - 66555665