server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        # Ruta para el servicio de autenticaci贸n
        - id: auth-service-route
          uri: http://auth-service-container:8084
          predicates:
            - Path=/auth/**
          filters:  
            - StripPrefix=1

        # Ruta al servicio de pacientes usando el nombre del contenedor
        - id: patient-service-route
          uri: http://patient-service-container:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Ruta para la documentaci贸n del servicio de pacientes 
        - id: api-docs-patient-route
          uri: http://patient-service-container:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients/(?<segment>.*), /${segment}

        # Ruta para la documentaci贸n del servicio de autenticaci贸n
        - id: api-docs-auth-route
          uri: http://auth-service-container:8084
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/index.html