server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/auth/**
          filters:  
            - StripPrefix=1

        - id: patient-service-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients/(?<segment>.*), "/${segment}"

        - id: api-docs-auth-route
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), "/${segment}"
